[package]
name = "alcubierre-derive"
version = "0.1.0"
authors = ["mrobakowski <mikolaj.rob@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.30", features = ["full", "extra-traits"] }
quote = "0.6.12"